dist: xenial
language: cpp
addons:
  apt:
    packages:
    - python-serial
    - gperf
# note that we clobber $PATH completely, to get rid of /opt/python* stuff so
# we can use the system python and python-serial, rather than messing around
# with pip all over the place
install:
  - export PATH=/bin:/usr/bin:/sbin:/usr/sbin
  - ./install.sh
script:
- export BUILD_DATE=$(date +%Y%m%d)
- cp sdkconfig.defaults sdkconfig
- make IDFPY_ARGS="-B build/float"
- echo CONFIG_LUA_NUMBER_INTEGRAL=y >> sdkconfig
- make IDFPY_ARGS="-B build/integer"
# http://docs.travis-ci.com/user/environment-variables/#Convenience-Variables
#- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash "$TRAVIS_BUILD_DIR"/tools/pr-build.sh; fi
